import Link from 'next/link'
import { ArrowRight, BarChart3, CircleCheck, Globe2, Search, Send, Sparkles } from 'lucide-react'
import type { SitePost } from '@/lib/site-connector'
import type { HomeTimeSection } from '@/lib/task-data'
import type { TaskKey } from '@/lib/site-config'
import { SITE_CONFIG } from '@/lib/site-config'
import { getEditableCategory, getEditableExcerpt, getEditablePostImage, postHref } from '@/editable/cards/PostCards'

type HomeSectionProps = { primaryTask: TaskKey; primaryRoute: string; posts: SitePost[]; timeSections: HomeTimeSection[] }

export function EditableHomeHero({ primaryTask, primaryRoute, posts }: HomeSectionProps) {
  const lead = posts[0]
  return (
    <section className="premium-grid relative -mt-[82px] overflow-hidden border-b border-white/8 bg-[#090a0c] px-4 pb-16 pt-40 text-center text-white sm:pb-24 sm:pt-48">
      <div className="pointer-events-none absolute left-1/2 top-20 h-[420px] w-[760px] -translate-x-1/2 rounded-full bg-[#ff6a1c]/10 blur-[130px]" />
      <div className="relative mx-auto max-w-[1120px]">
        <p className="text-[11px] font-black uppercase tracking-[.25em] text-[#ffae56]">Media distribution, made deliberate</p>
        <h1 className="editorial-serif mx-auto mt-6 max-w-[1060px] text-5xl font-black leading-[.96] tracking-[-.055em] sm:text-7xl lg:text-[5.65rem]">Plan, publish, and amplify stories that deserve attention.</h1>
        <p className="mx-auto mt-7 max-w-2xl text-base leading-8 text-white/58 sm:text-lg">A focused distribution platform for publishing releases, reaching new audiences, and keeping every media story easy to discover.</p>
        <div className="mt-9 flex flex-wrap justify-center gap-3"><Link href="/search" className="rounded-full bg-[#ff6a1c] px-7 py-4 text-xs font-black uppercase tracking-[.12em] shadow-[0_14px_40px_rgba(255,106,28,.35)] hover:bg-[#ffae56] hover:text-black">Explore releases</Link><Link href="/create" className="rounded-full border border-white/18 bg-white/5 px-7 py-4 text-xs font-black uppercase tracking-[.12em] hover:bg-white hover:text-black">Distribute a story</Link></div>
        <div className="orange-glow mx-auto mt-14 max-w-[920px] overflow-hidden rounded-[2rem] border border-white/12 bg-[#121318] p-2 text-left shadow-2xl">
          {lead ? <Link href={postHref(primaryTask, lead, primaryRoute)} className="group grid overflow-hidden rounded-[1.55rem] bg-[#0c0d0f] md:grid-cols-[1.2fr_.8fr]"><div className="relative min-h-[300px] overflow-hidden"><img src={getEditablePostImage(lead)} alt={lead.title} className="absolute inset-0 h-full w-full object-cover opacity-75 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-transparent to-transparent"/><span className="absolute left-5 top-5 rounded-full bg-[#ff6a1c] px-3 py-1.5 text-[10px] font-black uppercase tracking-[.16em]">Featured release</span></div><div className="flex flex-col justify-center p-7 sm:p-9"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#ffae56]">{getEditableCategory(lead)}</p><h2 className="editorial-serif mt-4 text-3xl font-black leading-[1.03] tracking-[-.04em]">{lead.title}</h2><p className="mt-5 text-sm leading-7 text-white/52">{getEditableExcerpt(lead, 175)}</p><span className="mt-6 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-[#ff6a1c]">Read release <ArrowRight className="h-4 w-4"/></span></div></Link> : <div className="grid min-h-[360px] place-items-center p-8"><div><Sparkles className="mx-auto h-8 w-8 text-[#ff6a1c]"/><h2 className="mt-4 text-2xl font-black">Your next headline starts here.</h2></div></div>}
        </div>
      </div>
    </section>
  )
}

export function EditableStoryRail({ primaryTask, primaryRoute, posts }: HomeSectionProps) {
  const items = posts.slice(1, 6)
  return <section className="bg-[#0d0e11] py-20 text-white"><div className="mx-auto max-w-[1120px] px-4 sm:px-6"><div className="grid gap-8 text-center md:grid-cols-3">{[[Globe2,'Expand your reach','Put releases in front of audiences exploring trusted media.'],[BarChart3,'Build lasting visibility','Give every announcement a polished, searchable destination.'],[Send,'Move stories forward','Keep distribution clear from publication through discovery.']].map(([Icon,title,copy]) => { const I=Icon as typeof Globe2; return <div key={String(title)}><div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl border border-white/10 bg-white/5 text-[#ff6a1c]"><I className="h-6 w-6"/></div><h2 className="editorial-serif mt-6 text-2xl font-black">{String(title)}</h2><p className="mx-auto mt-3 max-w-xs text-sm leading-6 text-white/48">{String(copy)}</p></div>})}</div>{items.length ? <div className="mt-20"><div className="flex items-end justify-between border-b border-white/12 pb-5"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#ffae56]">Latest dispatches</p><h2 className="editorial-serif mt-2 text-4xl font-black">Stories in motion</h2></div><Link href="/search" className="hidden text-xs font-black uppercase tracking-[.14em] sm:flex">View all <ArrowRight className="ml-2 h-4 w-4"/></Link></div><div className="mt-6 grid gap-4 lg:grid-cols-[1.45fr_repeat(3,.7fr)]">{items.slice(0,4).map((post,index)=><Link key={post.id||post.slug} href={postHref(primaryTask,post,primaryRoute)} className={`group relative overflow-hidden rounded-2xl bg-[#17181c] ${index===0?'min-h-[360px] lg:row-span-1':'min-h-[280px]'}`}><img src={getEditablePostImage(post)} alt={post.title} className="absolute inset-0 h-full w-full object-cover opacity-55 transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black via-black/15 to-transparent"/><div className="absolute inset-x-0 bottom-0 p-5"><p className="text-[9px] font-black uppercase tracking-[.18em] text-[#ffae56]">{getEditableCategory(post)}</p><h3 className={`${index===0?'text-3xl':'text-lg'} editorial-serif mt-2 font-black leading-tight`}>{post.title}</h3></div></Link>)}</div></div>:null}</div></section>
}

export function EditableMagazineSplit({ primaryTask, primaryRoute, posts }: HomeSectionProps) {
  const items=posts.slice(5,8).length?posts.slice(5,8):posts.slice(0,3)
  return <section className="bg-[#f3eee5] py-20 text-[#171719] sm:py-24"><div className="mx-auto max-w-[1120px] px-4 sm:px-6"><div className="text-center"><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#f05d16]">Built for modern distribution</p><h2 className="editorial-serif mx-auto mt-4 max-w-4xl text-4xl font-black tracking-[-.045em] sm:text-6xl">One publishing flow. Many ways to be discovered.</h2><p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-black/55">Create a permanent home for each release while keeping timely coverage easy to browse and share.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{items.map((post,index)=><Link key={post.id||post.slug} href={postHref(primaryTask,post,primaryRoute)} className={`group overflow-hidden rounded-[2rem] border border-black/10 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${index===1?'md:translate-y-8':''}`}><div className="aspect-[16/11] overflow-hidden bg-black"><img src={getEditablePostImage(post)} alt={post.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/></div><div className="p-6"><span className="text-[10px] font-black uppercase tracking-[.18em] text-[#f05d16]">0{index+1} / {getEditableCategory(post)}</span><h3 className="editorial-serif mt-3 text-2xl font-black leading-tight">{post.title}</h3><p className="mt-4 line-clamp-3 text-sm leading-6 text-black/55">{getEditableExcerpt(post,150)}</p></div></Link>)}</div></div></section>
}

export function EditableTimeCollections({ primaryTask, primaryRoute, posts, timeSections }: HomeSectionProps) {
  const source=timeSections.flatMap(s=>s.posts).length?timeSections.flatMap(s=>s.posts):posts
  return <section className="bg-[#0b0c0e] py-20 text-white"><div className="mx-auto max-w-[1120px] px-4 sm:px-6"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-[10px] font-black uppercase tracking-[.22em] text-[#ffae56]">From scattered outreach to planned publishing</p><h2 className="editorial-serif mt-4 text-4xl font-black leading-[1.02] tracking-[-.04em] sm:text-5xl">A clearer home for every announcement.</h2><div className="mt-8 grid gap-4">{['Publish with a consistent editorial structure','Organize releases by topic and category','Keep every story accessible and ready to share'].map(item=><p key={item} className="flex items-center gap-3 text-sm text-white/62"><CircleCheck className="h-5 w-5 shrink-0 text-[#ff6a1c]"/>{item}</p>)}</div></div><div className="rounded-[2rem] border border-white/10 bg-[#141519] p-4"><div className="rounded-[1.5rem] border border-white/8 bg-[#0c0d0f] p-6"><div className="flex items-center justify-between border-b border-white/10 pb-4"><span className="text-xs font-black uppercase tracking-[.16em]">Distribution board</span><span className="rounded-full bg-[#ff6a1c]/15 px-3 py-1 text-[10px] font-bold text-[#ffae56]">Live archive</span></div><div className="mt-4 space-y-3">{source.slice(0,4).map((post,index)=><Link key={post.id||post.slug} href={postHref(primaryTask,post,primaryRoute)} className="grid grid-cols-[38px_1fr_auto] items-center gap-3 rounded-xl border border-white/7 bg-white/[.025] p-3 hover:border-[#ff6a1c]/50"><span className="text-lg font-black text-[#ff6a1c]">0{index+1}</span><span className="line-clamp-1 text-sm font-bold">{post.title}</span><ArrowRight className="h-4 w-4 text-white/30"/></Link>)}</div></div></div></div><form action="/search" className="mt-16 grid gap-5 rounded-[2rem] border border-white/10 bg-gradient-to-r from-[#17181c] to-[#21130c] p-7 sm:grid-cols-[1fr_auto] sm:items-center sm:p-9"><div><h3 className="editorial-serif text-3xl font-black">Search the release archive</h3><p className="mt-2 text-sm text-white/48">Find companies, topics, announcements, and media updates.</p></div><label className="flex overflow-hidden rounded-full border border-white/15 bg-black/25 sm:min-w-[390px]"><Search className="ml-4 mt-4 h-4 w-4 text-[#ffae56]"/><input name="q" placeholder="Search releases" className="min-w-0 flex-1 bg-transparent px-3 py-3 text-sm outline-none"/><button className="m-1 rounded-full bg-[#ff6a1c] px-5 text-xs font-black">Search</button></label></form></div></section>
}

export function EditableHomeCta() { return <section className="bg-[#f3eee5] px-4 py-20 text-[#171719]"><div className="mx-auto flex max-w-[1080px] flex-col items-center justify-between gap-7 rounded-[2rem] border border-black/10 bg-white p-8 shadow-xl sm:p-10 lg:flex-row"><div><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#f05d16]">Ready when your story is</p><h2 className="editorial-serif mt-3 text-4xl font-black tracking-[-.04em]">Start planning your next release.</h2><p className="mt-3 text-sm text-black/50">Create an account and give your announcement a polished public home.</p></div><Link href="/signup" className="shrink-0 rounded-full bg-[#ff6a1c] px-8 py-4 text-xs font-black uppercase tracking-[.12em] text-white shadow-[0_12px_30px_rgba(255,106,28,.3)]">Get started</Link></div></section> }
